//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//

// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation

// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations

public struct Localizations {

    /// Base translation: Sunday
    public static var sunday: String = NSLocalizedString("sunday", comment: "")

    /// Base translation: Summersemester
    public static var summerSemester: String = NSLocalizedString("summerSemester", comment: "")

    /// Base translation: Saturday
    public static var saturday: String = NSLocalizedString("saturday", comment: "")

    /// Base translation: Schedule
    public static var scheduleTitle: String = NSLocalizedString("scheduleTitle", comment: "")

    /// Base translation: Thursday
    public static var thursday: String = NSLocalizedString("thursday", comment: "")

    /// Base translation: Friday
    public static var friday: String = NSLocalizedString("friday", comment: "")

    /// Base translation: Grades
    public static var gradesTitle: String = NSLocalizedString("gradesTitle", comment: "")

    /// Base translation: Monday
    public static var monday: String = NSLocalizedString("monday", comment: "")

    /// Base translation: Tuesday
    public static var tuesday: String = NSLocalizedString("tuesday", comment: "")

    /// Base translation: Wintersemester
    public static var winterSemester: String = NSLocalizedString("winterSemester", comment: "")

    /// Base translation: Wednesday
    public static var wednesday: String = NSLocalizedString("wednesday", comment: "")

    public struct Onboarding {

        public struct Welcome {

            /// Base translation: Welcome to HTW
            public static var Title: String = NSLocalizedString("Onboarding.Welcome.Title", comment: "")

            /// Base translation: View what your professors graded you in your exams.
            public static var GradesDescription: String = NSLocalizedString("Onboarding.Welcome.GradesDescription", comment: "")

            /// Base translation: See what is being served for lunch in the canteens around you.
            public static var CanteenDescription: String = NSLocalizedString("Onboarding.Welcome.CanteenDescription", comment: "")

            /// Base translation: Your schedule shows you all your lectures.
            public static var ScheduleDescription: String = NSLocalizedString("Onboarding.Welcome.ScheduleDescription", comment: "")

        }
    }
}
