fastlane_version "1.109.0"

default_platform :ios

platform :ios do
  before_all do
    
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "HTWDD")
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
