fastlane_version '1.100.0'

default_platform :ios

platform :ios do
  before_all do
    carthage(
      command: 'update',
      platform: 'iOS'
    )
  end

  desc 'Runs all the tests'
  lane :test do
    scan(
      skip_build: true,
      scheme: 'HTWDD',
      devices: ['iPhone SE']
    )
  end

  after_all do |lane|
    slack
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
